# This workflow is used to test events that trigger workflows #

name: Events

on:
  repository_dispatch:

  release:
    types: [prereleased]

  schedule:
    - cron: '0 15 * * *'

  label:
    types: [created, deleted, edited]

  milestone:
    types: [created, opened, edited]

  issues:
    types: [opened, reopened, labeled]

  issue_comment:
    types: [created, edited]

env:
  MSG: Hello
  NINJA_VER: 1.9.0
  ACTION_TRIGGER: false
  API_TRIGGER: false
  REPOSITORY_DISPATCH: false

jobs:
  workflow_run_info:
    name: Information about the workflow run
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show Information
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo "***********************************************************************************"
          echo "$env:GITHUB_CONTEXT"
          echo "==================================================================================="
          echo "Runner info:"
          echo "$env:RUNNER_CONTEXT"
          echo "***********************************************************************************"

  test_env_var:
    name: Test environment variable
    runs-on: windows-latest
    steps:
    - name: Print environment variable with cmd 
      if: env.MSG == 'Hello'
      run: echo "String matches %MSG%"
      shell: cmd

    - name: Print environment variable with powershell 
      run: echo "String matches $env:MSG"
      shell: powershell

    - name: Print environment variable with bash 
      run: echo "String matches $MSG"
      shell: bash

    - name: Print environment variable with pwsh 
      run: echo "String matches ${env:MSG}"  # Use $env:MSG also can work
      shell: pwsh

    - name: Print environment variable with python
      run: |
        import os
        print("String matches", os.environ['MSG'])
      shell: python

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@master
      with:
        version: ${{ env.NINJA_VER }}

  test_matrix:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        exclude: 
        - os: macos-latest
          TARGET: armv7-unknown-linux-musleabihf
        - os: macos-latest
          TARGET: x86_64-unknown-linux-musl
        - os: ubuntu-latest
          TARGET: x86_64-apple-darwin
    steps:
    - name: Building [ ${{ matrix.os }}, ${{ matrix.TARGET }} ]
      run: echo "Building [ ${{ matrix.os }}, ${{ matrix.TARGET }} ]"

  trigger_azure_pipeline_run:
    name: Trigger Azure pipeline run
    runs-on: windows-latest
    env:
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
    steps:
      - name: Trigger via action
        if: env.ACTION_TRIGGER == 'true'
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/TestNewFeature/PrimaryProj'
          azure-pipeline-name: 'TestClock'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Trigger via API
        if: env.API_TRIGGER == 'true'
        shell: pwsh
        run: |
          $definitionId = "8"
          $definitionName = "ShowDateTime"
          $pat = $env:AZURE_DEVOPS_PAT
          $apiUri = "https://dev.azure.com/TestNewFeature/PrimaryProj/_apis/build/builds?api-version=5.1"
          $body = "{
          	`"definition`": {
          		`"id`": $definitionId,
          		`"name`": `"$definitionName`"
          	}
          }"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $pat)))
          $Result = Invoke-RestMethod -Uri $apiUri -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Body $body -Method POST

  trigger_github_workflow_run:
    name: Trigger GitHub workflow run
    runs-on: windows-latest
    env:
      MY_PAT: ${{ secrets.MY_PAT }}
    steps:
      - name: Create a repository dispatch event to trigger workflow
        if: env.REPOSITORY_DISPATCH == 'true'
        shell: pwsh
        run: |
          $pat = $env:MY_PAT
          $uri = "https://api.github.com/repos/BrightRan/TestClock/dispatches"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $pat)))
          
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
          $headers.Add("Authorization", ("Basic {0}" -f $base64AuthInfo))
          $headers.Add("Accept", "application/vnd.github.everest-preview+json")
          $headers.Add("Content-Type", "application/json")
          
          $body = "{
            `"event_type`": `"test-repository-dispatch`",
            `"client_payload`": {
              `"unit`": false,
              `"integration`": true
            }
          }"
          
          $response = Invoke-RestMethod -Uri $uri -Headers $headers -Body $body -Method POST
          $response | ConvertTo-Json